// ============================================================
// activate-invitation — Edge Function
// ============================================================
// Called from the activation screen with { code, password, deviceName }.
// Runs with SERVICE_ROLE so it can:
//   1. Validate the invitation code (not used, not expired)
//   2. Create the auth user
//   3. Create the matching profile row (with conjunto_id, role, etc)
//   4. If resident: create a device row linked to the assigned house
//   5. Mark the invitation as used
//   6. Sign in and return the session so the client logs in immediately
//
// Security model: this is the ONLY way to create users + profiles in Atrio.
// There is no client-side signUp. All access is gated by valid invitations
// generated by admins of the conjunto.
// ============================================================

import { createClient } from 'npm:@supabase/supabase-js@2';
import { handleCors, json } from '../_shared/cors.ts';

const SUPABASE_URL         = Deno.env.get('SUPABASE_URL')!;
const SUPABASE_SERVICE_ROLE = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;

// Admin client (bypasses RLS)
const admin = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE, {
  auth: { autoRefreshToken: false, persistSession: false },
});

interface ActivatePayload {
  code: string;
  password: string;
  deviceName?: string;
}

Deno.serve(async (req: Request) => {
  const cors = handleCors(req);
  if (cors) return cors;

  if (req.method !== 'POST') {
    return json({ error: 'Method not allowed' }, 405);
  }

  let payload: ActivatePayload;
  try {
    payload = await req.json();
  } catch {
    return json({ error: 'Invalid JSON body' }, 400);
  }

  const { code, password, deviceName } = payload;
  if (!code || !password) {
    return json({ error: 'Faltan datos (código y contraseña son obligatorios)' }, 400);
  }
  if (password.length < 4) {
    return json({ error: 'La contraseña debe tener al menos 4 caracteres' }, 400);
  }

  const normalizedCode = code.trim().toUpperCase();

  // 1. Validate invitation
  const { data: inv, error: invErr } = await admin
    .from('invitations')
    .select('*')
    .eq('code', normalizedCode)
    .single();

  if (invErr || !inv) {
    return json({ error: 'Código inválido o no encontrado' }, 404);
  }
  if (inv.used) {
    return json({ error: 'Este código ya fue utilizado' }, 410);
  }
  if (new Date(inv.expires_at) < new Date()) {
    return json({ error: 'Este código ha expirado. Pide uno nuevo al administrador.' }, 410);
  }

  // 2. Check that the email is not already taken
  const { data: existingProfile } = await admin
    .from('profiles')
    .select('id')
    .eq('email', inv.email.toLowerCase())
    .maybeSingle();
  if (existingProfile) {
    return json({ error: 'Ya existe una cuenta con este correo' }, 409);
  }

  // 3. For resident: check that the house still has room for one more device
  if (inv.role === 'resident' && inv.house_id) {
    const { count } = await admin
      .from('devices')
      .select('*', { count: 'exact', head: true })
      .eq('house_id', inv.house_id);
    if ((count ?? 0) >= 2) {
      return json({ error: 'Esta casa ya alcanzó el máximo de 2 dispositivos.' }, 409);
    }
  }

  // 4. Create the auth user (auto-confirmed since we're trusting the invitation)
  const { data: userData, error: userErr } = await admin.auth.admin.createUser({
    email: inv.email.toLowerCase(),
    password,
    email_confirm: true,
  });
  if (userErr || !userData?.user) {
    console.error('createUser failed:', userErr);
    return json({ error: 'No se pudo crear la cuenta: ' + (userErr?.message || 'error') }, 500);
  }
  const newUserId = userData.user.id;

  // 5. Derive a readable name from the email if none provided
  const derivedName = inv.email
    .split('@')[0]
    .replace(/[._-]/g, ' ')
    .replace(/\b\w/g, (l: string) => l.toUpperCase());

  // 6. Create the profile
  const profileRow: Record<string, unknown> = {
    id: newUserId,
    conjunto_id: inv.conjunto_id,
    email: inv.email.toLowerCase(),
    name: derivedName,
    role: inv.role,
    active: true,
  };
  if (inv.role === 'admin')    profileRow.admin_level = inv.admin_level ?? 2;
  if (inv.role === 'guard')    profileRow.shift       = inv.shift ?? 'day';
  if (inv.role === 'resident') profileRow.house_id    = inv.house_id;

  const { error: profErr } = await admin.from('profiles').insert(profileRow);
  if (profErr) {
    console.error('profile insert failed:', profErr);
    // Roll back: delete the auth user we just created
    await admin.auth.admin.deleteUser(newUserId);
    return json({ error: 'No se pudo crear el perfil: ' + profErr.message }, 500);
  }

  // 7. For residents: create the device and link it to the profile
  let deviceId: string | null = null;
  if (inv.role === 'resident' && inv.house_id) {
    const fingerprint =
      Math.random().toString(36).slice(2, 6).toUpperCase() + '-' +
      Math.random().toString(36).slice(2, 6).toUpperCase();

    const { data: dev, error: devErr } = await admin
      .from('devices')
      .insert({
        conjunto_id: inv.conjunto_id,
        house_id: inv.house_id,
        user_id: newUserId,
        name: (deviceName?.trim() || 'Mi dispositivo'),
        fingerprint,
      })
      .select('id')
      .single();

    if (devErr) {
      console.error('device insert failed:', devErr);
      // Roll back profile + auth user
      await admin.from('profiles').delete().eq('id', newUserId);
      await admin.auth.admin.deleteUser(newUserId);
      return json({ error: 'No se pudo registrar el dispositivo: ' + devErr.message }, 500);
    }
    deviceId = dev.id;

    await admin
      .from('profiles')
      .update({ device_id: deviceId })
      .eq('id', newUserId);
  }

  // 8. Mark the invitation as used
  await admin
    .from('invitations')
    .update({
      used: true,
      used_at: new Date().toISOString(),
      used_by: newUserId,
    })
    .eq('code', normalizedCode);

  // 9. Audit log entry
  await admin.from('audit_log').insert({
    conjunto_id: inv.conjunto_id,
    actor_id: newUserId,
    actor_email: inv.email.toLowerCase(),
    event_type: 'user_activated',
    detail: {
      role: inv.role,
      house_id: inv.house_id,
      invitation_code: normalizedCode,
    },
  });

  // 10. Generate a session for the new user so the client logs in immediately
  const { data: sessionData, error: sessErr } = await admin.auth.admin.generateLink({
    type: 'magiclink',
    email: inv.email.toLowerCase(),
  });

  // Fallback: if generateLink doesn't return a session, the client can sign in
  // with email + password (which we just set above).
  let session = null;
  if (!sessErr && sessionData) {
    // Sign in via password (more reliable than parsing magiclink)
    const { data: signInData } = await admin.auth.signInWithPassword({
      email: inv.email.toLowerCase(),
      password,
    });
    session = signInData?.session ?? null;
  }

  return json({
    ok: true,
    user_id: newUserId,
    role: inv.role,
    conjunto_id: inv.conjunto_id,
    session, // { access_token, refresh_token } — client sets these
  });
});
